# Generated by Django 4.0.5 on 2022-06-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_faced', models.TextField()),
                ('special_requests', models.TextField()),
                ('beneficiary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.beneficiary')),
                ('volunteer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volunteer.profile')),
            ],
        ),
    ]
